//generate items based on difficulty modifier and item find

export function generateItem(difficulty, itemFind){
    const itemTypes = [helmet, body, boot, glove, shoulder, ring, pants, belt, amulet, backpack, bracelet, sock, underwear, undershirt, cloak, glasses];
    const itemMultipliers = {
        helmet: 5,
        body: 10,
        boot: 3,
        glove: 3,
        shoulder: 3,
        ring: 2,
        pants: 8,
        belt: 5,
        amulet: 8,
        backpack: 5,
        bracelet: 2,
        sock: 1,
        underwear: 2,
        undershirt: 2,
        cloak: 4,
        glasses: 3,
    }
    const powerStatBase = [1,2];
    const weakStatBase = [1,5];
    const stats = {
        "strength" : weakStatBase,
        "strength%" : powerStatBase,
        "intelligence" : weakStatBase,
        "intelligence%" : powerStatBase,
        "agility" : weakStatBase,
        "agility%" : powerStatBase,
        "allStats" : weakStatBase,
        "allStats%" : powerStatBase,
        "health" : [10, 100],
        "health%": powerStatBase,
        "armor": weakStatBase,
        "armor%": powerStatBase,
        "damage": weakStatBase,
        "damage%": powerStatBase,
        "critChance": powerStatBase,
        "critDamage": powerStatBase,
        "attackSpeed": powerStatBase,
        "thorns": weakStatBase,
        "damageResist": powerStatBase,
        "allResist": powerStatBase,
        "fireResist": weakStatBase,
        "physicalResist": weakStatBase,
        "coldResist": weakStatBase,
        "lightningResist": weakStatBase,
        "psychicResist": weakStatBase,
        "poisonResist": weakStatBase,
        "chanceToBleed": weakStatBase,
        "chanceToPoison": weakStatBase,
        "chanceToBurn": weakStatBase,
        "chanceToElectrocute": weakStatBase,
        "chanceToFreeze": weakStatBase,
        "chanceToStun": weakStatBase,
        "chanceToExecute": weakStatBase,
        "lifeRegeneration": powerStatBase,
        "lifeOnKill": weakStatBase,
        "lifeOnHit": powerStatBase,
        "itemDrop%": [1,20],
        "goldDrop%": [1,20],
        "inventorySpace": [1,1],
    }
}